url: http://example.com
username: demo
password: demo
one_shot: false
run_time: now
jitter_minute: 10
start:
  hour: 9
  minute: 15
end:
  hour: 21
  minute: 45
delay_minute: 45
exclude_weekdays:
  - 5
  - 6
